-- Regeln anzeigen lassen (Konfidenz/Support) -- SCHMUTZ
SELECT PRODUKT_ID, SKU, RULE_ID, ITEMS_BASE, ITEMS_ADD, CONFIDENCE, LIFT, SUPPORT FROM ASSOANREDEFRAU, PRODUKT
WHERE REPLACE(REPLACE(ITEMS_BASE, '{', ''), '}', '') = PRODUKT.SKU;


(SELECT PRODUKT_ID as BASE_PRODUKT_ID, SKU as BASE_SKU, RULE_ID, ITEMS_BASE, ITEMS_ADD, CONFIDENCE, LIFT, SUPPORT FROM ASSOANREDEFRAU, PRODUKT
WHERE REPLACE(REPLACE(ITEMS_BASE, '{', ''), '}', '') = PRODUKT.SKU)
UNION
(SELECT PRODUKT_ID as ADD_PRODUKT_ID, SKU as ADD_SKU, RULE_ID, ITEMS_BASE, ITEMS_ADD, CONFIDENCE, LIFT, SUPPORT FROM ASSOANREDEFRAU, PRODUKT
WHERE REPLACE(REPLACE(ITEMS_ADD, '{', ''), '}', '') = PRODUKT.SKU);


-- Kundenranking (Rezension)
SELECT KUNDE.NACHNAME, REZENSION.KUNDENKONTO_ID, COUNT(REZENSION.REZENSION_ID)
FROM REZENSION, KUNDENKONTO, KUNDE
WHERE REZENSION.KUNDENKONTO_ID = KUNDENKONTO.KUNDENKONTO_ID AND KUNDE.KUNDE_ID = KUNDENKONTO.KUNDE_ID
group by REZENSION.KUNDENKONTO_ID, KUNDE.NACHNAME order by COUNT(REZENSION.REZENSION_ID) DESC;

-- Kundenranking (Umsatz)
SELECT KUNDE.NACHNAME, KUNDE.KUNDE_ID, sum(RECHNUNG.SUMME_BRUTTO)
FROM KUNDE, WARENKORB, BESTELLPOSITION, BESTELLUNG, RECHNUNG
WHERE KUNDE.KUNDE_ID = WARENKORB.KUNDE_ID AND WARENKORB.WARENKORB_ID = BESTELLUNG.WARENKORB_ID AND BESTELLUNG.BESTELLUNG_ID = RECHNUNG.RECHNUNG_ID AND BESTELLUNG.BESTELLUNG_ID= BESTELLPOSITION.BESTELLUNG_ID
group by KUNDE.NACHNAME, KUNDE.KUNDE_ID order by sum(RECHNUNG.SUMME_BRUTTO) DESC;

-- Produktranking
SELECT PRODUKT_ID, RANKING
FROM PRODUKT order by RANKING DESC;

-- Käufe auf Zeit - Chart
select TRUNC(RECHNUNGSDATUM), count(RECHNUNG_ID) as ANZAHL_KAEUFE
from RECHNUNG
where RECHNUNGSDATUM between sysdate - 100 AND sysdate
group by TRUNC(RECHNUNGSDATUM);

-- Umsatz auf Zeit - Chart
select TRUNC(RECHNUNGSDATUM), sum(SUMME_BRUTTO) as GESAMT_UMSATZ_BRUTTO
from RECHNUNG
where RECHNUNGSDATUM between sysdate - 100 AND sysdate
group by TRUNC(RECHNUNGSDATUM);

-- Meistverkaufteste Produkte - NICHT KORREKT DA MENGE FEHLT -- SCHMUTZ
SELECT BESTELLPOSITION.PRODUKT_ID, COUNT(BESTELLPOSITION.PRODUKT_ID)
FROM BESTELLPOSITION,
     BESTELLUNG
WHERE BESTELLPOSITION.BESTELLUNG_ID = BESTELLUNG.BESTELLUNG_ID
group by BESTELLPOSITION.PRODUKT_ID;

-- Umsatz - täglich/monatlich/gesamt
select sum(SUMME_BRUTTO) as GESAMT_UMSATZ_BRUTTO
from RECHNUNG
where RECHNUNGSDATUM between sysdate - 100 AND sysdate

-- Anzahl an Bestellungen - täglich/monatlich/gesamt
SELECT COUNT(Distinct BESTELLUNG_ID)
FROM BESTELLUNG
Where BESTELLDATUM between sysdate - 1 AND sysdate;

SELECT COUNT(Distinct BESTELLUNG_ID)
FROM BESTELLUNG
Where BESTELLDATUM between add_months(trunc(sysdate, 'mm'), -1) and last_day(add_months(trunc(sysdate, 'mm'), -1));

select COUNT(BESTELLUNG_ID)
FROM BESTELLPOSITION;
