# Generated by Django 3.2.11 on 2022-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('adresse_id', models.FloatField(db_column='adresse_id', primary_key=True, serialize=False)),
                ('land', models.CharField(db_column='land', max_length=40)),
                ('plz', models.CharField(db_column='plz', max_length=10)),
                ('ort', models.CharField(db_column='ort', max_length=40)),
                ('strasse', models.CharField(db_column='strasse', max_length=40)),
                ('hausnummer', models.CharField(db_column='hausnummer', max_length=10)),
                ('bundesland', models.CharField(blank=True, db_column='bundesland', max_length=255, null=True)),
            ],
            options={
                'db_table': 'adresse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.FloatField(db_column='kunde_id', primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, db_column='anrede', max_length=20, null=True)),
                ('firstname', models.CharField(db_column='vorname', max_length=100)),
                ('lastname', models.CharField(db_column='nachname', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100)),
                ('birth_date', models.DateField(blank=True, db_column='geburtsdatum', null=True)),
            ],
            options={
                'db_table': 'kunde',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('customer_address_id', models.FloatField(db_column='kunde_adresse_id', primary_key=True, serialize=False)),
                ('address_type', models.CharField(blank=True, db_column='adressart', max_length=100, null=True)),
            ],
            options={
                'db_table': 'kunde_adresse',
                'managed': False,
            },
        ),
    ]
