# Generated by Django 3.2.11 on 2022-02-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('product_category_id', models.FloatField(db_column='produkt_kategorie_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='bezeichnung', max_length=50)),
                ('slug', models.SlugField(default='test')),
            ],
            options={
                'db_table': 'produkt_kategorie',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('product_family_id', models.FloatField(db_column='produkt_familie_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='bezeichnung', max_length=50)),
                ('slug', models.SlugField(default='test')),
            ],
            options={
                'db_table': 'produkt_familie',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('product_subcategory_id', models.FloatField(db_column='produkt_subkategorie_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='bezeichnung', max_length=50)),
                ('slug', models.SlugField(default='test')),
                ('product_category', models.ForeignKey(blank=True, db_column='produkt_kategorie_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='product.productcategory')),
            ],
            options={
                'db_table': 'produkt_subkategorie',
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='ProductDivision',
            fields=[
                ('product_division_id', models.FloatField(db_column='produkt_sparte_id', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='bezeichnung', max_length=50)),
                ('slug', models.SlugField(default='test')),
                ('product_family', models.ForeignKey(blank=True, db_column='produkt_familie_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='divisions', to='product.productfamily')),
            ],
            options={
                'db_table': 'produkt_sparte',
                'ordering': ('description',),
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_division',
            field=models.ForeignKey(blank=True, db_column='produkt_sparte_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='product.productdivision'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.FloatField(db_column='produkt_id', default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='proukt_name', max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.CharField(blank=True, db_column='produktbeschreibung', max_length=500, null=True)),
                ('price', models.FloatField(db_column='listenverkaufspreis')),
                ('image', models.CharField(blank=True, db_column='produktbild_link', max_length=1000, null=True)),
                ('sku', models.FloatField(blank=True, db_column='sku', null=True)),
                ('evaluation', models.FloatField(blank=True, db_column='bewertung', null=True)),
                ('recycle', models.FloatField(blank=True, db_column='recyclebar', null=True)),
                ('lowfat', models.FloatField(blank=True, db_column='low_fat', null=True)),
                ('discount', models.FloatField(blank=True, db_column='angebotsrabatt', null=True)),
                ('origin', models.FloatField(blank=True, db_column='datenherkunft_id', null=True)),
                ('subcategory', models.ForeignKey(blank=True, db_column='produktklasse_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productsubcategory')),
            ],
            options={
                'db_table': 'produkt',
                'managed': 'true',
            },
        ),
    ]
