# Generated by Django 3.2.11 on 2022-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.FloatField(db_column='warenkorb_id', primary_key=True, serialize=False)),
                ('total_price', models.FloatField(db_column='gesamtpreis')),
                ('total_quantity', models.FloatField(blank=True, db_column='gesamtmenge', null=True)),
            ],
            options={
                'db_table': 'warenkorb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('cart_product_id', models.FloatField(db_column='warenkorb_produkt_id', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='menge')),
            ],
            options={
                'db_table': 'warenkorb_produkt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.FloatField(db_column='bestellung_id', primary_key=True, serialize=False)),
                ('order_date', models.DateField(db_column='bestelldatum')),
                ('total_quantity', models.FloatField(db_column='gesamtmenge')),
                ('origin', models.FloatField(blank=True, db_column='datenherkunft_id', null=True)),
            ],
            options={
                'db_table': 'bestellung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.FloatField(db_column='bestellposition_id', primary_key=True, serialize=False)),
                ('quantity', models.FloatField(db_column='menge')),
            ],
            options={
                'db_table': 'bestellposition',
                'managed': False,
            },
        ),
    ]
